export type MockServerData = {
  titles: string[],
  descriptions: string[],
  cities: string[],
  photos: string[],
  isPremium: boolean,
  isFavorite: boolean,
  types: string[],
  amenities: string[],
  names: string[],
  emails: string[],
  avatars: string[],
  passwords: string[],
  userTypes: string[],
}
